# Generated by Django 5.1.6 on 2025-03-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe", models.CharField(max_length=30)),
                ("difficulty", models.CharField(max_length=30)),
            ],
        ),
    ]
