# Generated by Django 4.2.5 on 2025-05-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemuser_age_systemuser_pronouns'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
