# Generated by Django 4.2.5 on 2025-05-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
