# Generated by Django 4.2.5 on 2025-05-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_step_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='step',
            name='step_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
