# Generated by Django 4.2.5 on 2025-06-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_comment_created_at_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.allergy'),
        ),
    ]
