# Generated by Django 4.2.5 on 2025-06-01 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_systemuser_allergies'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAllergyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.CharField(blank=True, help_text="Severity level of the allergy (e.g. 'mild', 'moderate', 'severe').", max_length=100)),
                ('symptoms', models.TextField(blank=True, help_text='Description of allergy symptoms.')),
                ('treatment', models.TextField(blank=True, help_text='Recommended treatment or management.')),
                ('allergy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_info', to='api.allergy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allergy_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'allergy')},
            },
        ),
    ]
