# Generated by Django 4.2.5 on 2025-07-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_recipe_cooking_time_recipe_created_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='spoonacular_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
