# Generated by Django 4.2.5 on 2025-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_recipe_spoonacular_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userallergyinfo',
            name='power',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userallergyinfo',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userallergyinfo',
            name='treatment',
            field=models.TextField(blank=True),
        ),
    ]
