# Generated by Django 4.2.5 on 2025-09-12 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientSubstitute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('ratio', models.FloatField(default=1.0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutes', to='api.ingredient')),
            ],
            options={
                'unique_together': {('ingredient', 'name')},
            },
        ),
    ]
