# Generated by Django 4.2.5 on 2025-09-12 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_ingredientsubstitute'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientsubstitute',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='priority',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='ingredientsubstitute',
            name='replaces_allergy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.allergy'),
        ),
        migrations.AlterField(
            model_name='ingredientsubstitute',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
