# Generated by Django 4.2.5 on 2025-09-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ingredientsubstitute_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='image',
            new_name='avatar',
        ),
    ]
